// import { AnimatePresence } from "framer-motion";
import FallingChocolateBg from "@/components/falling-chocolate-bg";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-italian-old-style">
        {/* Background falling chocolate image */}
        <FallingChocolateBg />
        <div className="mt-10">{children}</div>
      </body>
    </html>
  );
}
